### ISSUE TITLE
Feat: Better GitHub guide

### ISSUE THREAD

**Issue by BereketEngida** [Bekacru/getting-involved-in-open-source#2]
Hey I want tor request for better GitHub guide. The current one really lacks a lot of things.

**Comment by Bekacru** [comment]
Hey I'll get on it would love if you help on Github issues section!

**Comment by BereketEngida** [comment]
sure on it 👍

**Comment by Bekacru** [comment]
done!

**Comment by BereketEngida** [comment]
Thanks will get started 🙏🏼
